# Generated by Django 3.2.5 on 2021-09-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='ground',
            field=models.CharField(max_length=255),
        ),
    ]
