# Generated by Django 3.2.5 on 2021-09-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_stadium_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='team',
            field=models.CharField(max_length=255),
        ),
    ]
